# Generated by Django 5.0.6 on 2024-07-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_remove_transaction_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
