# Generated by Django 5.0.6 on 2024-07-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
